/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OnlineBookOrderSystem;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Aya
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        jPanel1.setVisible(false);
        try {
            connect_database con = connect_database.getInstance();
            String query1 = "SELECT * FROM category";
            ResultSet res = con.retrivedata(query1);

            // Create a list to store category names temporarily
            List<String> categoryNames = new ArrayList<>();

            while (res.next()) {
                String categoryName = res.getString("name");
                categoryNames.add(categoryName); // Store category names in a list
            }

            // Add category names to Category_filter after retrieving all data
            for (String categoryName : categoryNames) {
                Category_filter.addItem(categoryName);
            }
        } catch (Exception ex) {
            ex.printStackTrace(); // Print the exception trace for debugging
        }

        try {
            connect_database DB = connect_database.getInstance();
            ResultSet rs = DB.retrivedata("select book_name, author_name, edition, popularity,price, available_units from book");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Category_filter = new javax.swing.JComboBox<>();
        Popularity_sort = new javax.swing.JCheckBox();
        View_cart_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Add_reviews1_btn = new javax.swing.JButton();
        Add_cart1_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        photo1 = new javax.swing.JLabel();
        Price1_txt = new javax.swing.JTextField();
        Name1_txt = new javax.swing.JTextField();
        myProfile_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Jimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,120));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        Category_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_filterActionPerformed(evt);
            }
        });

        Popularity_sort.setText("Sort by popularity");
        Popularity_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popularity_sortActionPerformed(evt);
            }
        });

        View_cart_btn.setText("View Cart");
        View_cart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_cart_btnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        Add_reviews1_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Add_reviews1_btn.setText("Reviews");
        Add_reviews1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_reviews1_btnActionPerformed(evt);
            }
        });

        Add_cart1_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Add_cart1_btn.setText("Add to cart");
        Add_cart1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_cart1_btnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Name1_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Price1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(photo1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(photo1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        myProfile_btn.setText("My Profile");
        myProfile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfile_btnActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(myProfile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(View_cart_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Popularity_sort)
                .addGap(38, 38, 38)
                .addComponent(Category_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_reviews1_btn)
                .addGap(18, 18, 18)
                .addComponent(Add_cart1_btn)
                .addGap(104, 104, 104))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(490, Short.MAX_VALUE)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Add_cart1_btn, Add_reviews1_btn});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {View_cart_btn, jButton1});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Popularity_sort)
                    .addComponent(Category_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myProfile_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_cart_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_reviews1_btn)
                    .addComponent(Add_cart1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(305, 305, 305)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Add_cart1_btn, Add_reviews1_btn});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {View_cart_btn, jButton1});

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 880, 550));

        Jimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        Jimage.setText("jLabel5");
        Jimage.setMaximumSize(new java.awt.Dimension(1000, 1000));
        Jimage.setMinimumSize(new java.awt.Dimension(1000, 640));
        Jimage.setPreferredSize(new java.awt.Dimension(1000, 640));
        getContentPane().add(Jimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1020, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_reviews1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_reviews1_btnActionPerformed
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        String name = table.getValueAt(jTable1.getSelectedRow(), 0).toString();
        connect_database con = connect_database.getInstance();
        try {
            ResultSet rs = con.retrivedata("select id from book where book_name='" + name + "'");
            rs.next();
            int book_id = Integer.parseInt(rs.getString("id"));
            globalValue global = globalValue.getInstance();
            global.setBook_id_review(book_id);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        new Reviews().setVisible(true);
        dispose();
    }//GEN-LAST:event_Add_reviews1_btnActionPerformed

    private void View_cart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_cart_btnActionPerformed
        if (globalValue.getInstance().isLogedin()) {
            new Cart().setVisible(true);
            dispose();
        } else {
            new OnlineBookSystemUI().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_View_cart_btnActionPerformed

    private void Add_cart1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_cart1_btnActionPerformed
        connect_database con = connect_database.getInstance();
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int userID = globalValue.getInstance().getUser_id();
        try {
            String book_name = table.getValueAt(jTable1.getSelectedRow(), 0).toString();
            ResultSet rs = con.retrivedata("select id from book where book_name='" + book_name + "'");
            rs.next();
            int book_id = Integer.parseInt(rs.getString("id"));
            String query = "INSERT INTO cart_books values( '" + book_id + "', '" + userID + "')";
            con.queurydata(query);
            JOptionPane.showMessageDialog(null, "Book Added to Cart");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "You are not logged in");
        }
    }//GEN-LAST:event_Add_cart1_btnActionPerformed

    private void Category_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_filterActionPerformed
        String cname = Category_filter.getSelectedItem().toString();
        try {
            connect_database DB = connect_database.getInstance();
            ResultSet rs = DB.retrivedata("select id from category where name='" + cname + "'");
            rs.next();
            int cid = Integer.parseInt(rs.getString("id"));
            rs = DB.retrivedata("select book_name, author_name, edition, popularity,price,"
                    + " available_units from book where book_category = '" + cid + "'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Category_filterActionPerformed

    private void Popularity_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popularity_sortActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.getDataVector().sort(new Comparator<Vector>() {
            @Override
            public int compare(Vector o1, Vector o2) {
                // Assuming column 3 contains Integer values
                Integer value1 = (Integer) o1.get(3);
                Integer value2 = (Integer) o2.get(3);

                // Change the comparison logic based on your data type
                return value2.compareTo(value1); // Sort in descending order
            }
        });

// Fire table data changes to reflect the sorted order in the table
        model.fireTableDataChanged();

    }//GEN-LAST:event_Popularity_sortActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        String name = table.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String price = table.getValueAt(jTable1.getSelectedRow(), 4).toString();
        jPanel1.setVisible(true);
        Name1_txt.setText(name);
        Price1_txt.setText(price);
        connect_database DB = connect_database.getInstance();
        ResultSet rs;
        try {
            rs = DB.retrivedata("select book_cover from book where book_name='" + name + "'");
            rs.next();
            String cover = rs.getString("book_cover");
            BufferedImage myPicture = ImageIO.read(new File(cover));
            Image newImage = myPicture.getScaledInstance(88, 116, Image.SCALE_DEFAULT);
            ImageIcon cimage = new ImageIcon(newImage);

            photo1.setIcon(cimage);
        } catch (Exception ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void myProfile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfile_btnActionPerformed
        if (globalValue.getInstance().isLogedin()) {
            new UserForm().setVisible(true);
            dispose();
        } else {
            new OnlineBookSystemUI().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_myProfile_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new OnlineBookSystemUI().setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_cart1_btn;
    private javax.swing.JButton Add_reviews1_btn;
    private javax.swing.JComboBox<String> Category_filter;
    private javax.swing.JLabel Jimage;
    private javax.swing.JTextField Name1_txt;
    private javax.swing.JCheckBox Popularity_sort;
    private javax.swing.JTextField Price1_txt;
    private javax.swing.JButton View_cart_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton myProfile_btn;
    private javax.swing.JLabel photo1;
    // End of variables declaration//GEN-END:variables
}
